quarkus:
  log:
    category:
      "io.wybis":
        level: DEBUG
#  datasource:
#    db-kind: h2
#    username: sa
#    password:
#    jdbc:
#      url: jdbc:h2:tcp://localhost/~/app-home/block-trust/db/h2-dev;AUTO_SERVER=true;DB_CLOSE_DELAY=-1
#      max-size: 10